server:
  port: 8081
  shutdown: "graceful"
  servlet:
    context-path: /land
spring:
  application:
    name: land
  mvc:
    problemdetails:
      enabled: true
    log-request-details: true
    log-resolved-exception: true
  datasource:
    hikari:
      validation-timeout: 60000
      connection-test-query: select 1
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/x?useUnicode=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456789
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jackson:
    property-naming-strategy: SNAKE_CASE
    deserialization:
      read-unknown-enum-values-as-null: true
    serialization:
      write-dates-as-timestamps: false
dubbo:
  application:
    name: land
    protocol: injvm
    register-consumer: false
  provider:
    export: false
leaf:
  name: land
  segment:
    enable: true
    url: jdbc:mysql://localhost:3306/x
    username: root
    password: 123456789
mybatis-plus:
  global-config:
    db-config:
      column-format: "`%s`"
logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log
  threshold:
    console: INFO
    file: INFO
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 1024MB