### 注册
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "username": "xxd",
  "password": "123456",
  "confirmPassword": "123456"
}

### 登录
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "username": "xxd",
  "password": "123456"
}

### 当前用户
POST {{baseUrl}}/users/currentUser
Content-Type: application/json
Authorization: Bearer {{token}}