name: Land Project Deploy

on:
  workflow_dispatch:

jobs:
  deploy-land:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: "temurin"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.9

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package -DskipTests

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "land/target/*.jar,land/target/classes/*.yml,land/Dockerfile"
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1
          overwrite: true

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ env.DEPLOY_PATH }}

            # 停止并删除旧容器
            docker stop land || true
            docker rm land || true

            # 构建新镜像
            docker build -t land:latest .

            # 启动新容器
            docker run -d \
              --name land \
              -e "SPRING_PROFILES_ACTIVE=prod" \
              -p ${{ env.PORT }}:${{ env.PORT }} \
              -v ${{ env.DEPLOY_PATH }}/config:/app/config \
              -v ${{ env.DEPLOY_PATH }}/logs:/app/logs \
              land:latest

            # 清理
            docker image prune -f &
